// Generated by scripts/generate-social-emoji-assets.cjs. Do not edit.
export const SOCIAL_EMOJI_DEFINITIONS = [
  {
    "group": "challenge",
    "path": "res/challenge-icons/about.gif",
    "token": ":challenge/about:",
    "label": "about"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/alliteration.gif",
    "token": ":challenge/alliteration:",
    "label": "alliteration"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/as-close-as-it-gets.gif",
    "token": ":challenge/as-close-as-it-gets:",
    "label": "as close as it gets"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/ate-and-left-no-crumbs.gif",
    "token": ":challenge/ate-and-left-no-crumbs:",
    "label": "ate and left no crumbs"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/autodraw-detected.gif",
    "token": ":challenge/autodraw-detected:",
    "label": "autodraw detected"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/back-to-back.gif",
    "token": ":challenge/back-to-back:",
    "label": "back to back"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/better-late-than-never.gif",
    "token": ":challenge/better-late-than-never:",
    "label": "better late than never"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/big-word.gif",
    "token": ":challenge/big-word:",
    "label": "big word"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/blind-guess.gif",
    "token": ":challenge/blind-guess:",
    "label": "blind guess"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/bloodline.gif",
    "token": ":challenge/bloodline:",
    "label": "bloodline"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/bullet-skribbl-io.gif",
    "token": ":challenge/bullet-skribbl-io:",
    "label": "bullet skribbl io"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/caught-in-4k.gif",
    "token": ":challenge/caught-in-4k:",
    "label": "caught in 4k"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/checkmark.gif",
    "token": ":challenge/checkmark:",
    "label": "checkmark"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/color-picker.gif",
    "token": ":challenge/color-picker:",
    "label": "color picker"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/cool-number-detected.gif",
    "token": ":challenge/cool-number-detected:",
    "label": "cool number detected"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/copy-and-paste.gif",
    "token": ":challenge/copy-and-paste:",
    "label": "copy and paste"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/countdown_1.gif",
    "token": ":challenge/countdown_1:",
    "label": "countdown 1"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/countdown_2.gif",
    "token": ":challenge/countdown_2:",
    "label": "countdown 2"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/countdown_3.gif",
    "token": ":challenge/countdown_3:",
    "label": "countdown 3"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/countdown_4.gif",
    "token": ":challenge/countdown_4:",
    "label": "countdown 4"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/countdown_5.gif",
    "token": ":challenge/countdown_5:",
    "label": "countdown 5"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/countdown_ExclamationMark.gif",
    "token": ":challenge/countdown_exclamationmark:",
    "label": "countdown exclamationmark"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/countdown_G.gif",
    "token": ":challenge/countdown_g:",
    "label": "countdown g"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/countdown_O.gif",
    "token": ":challenge/countdown_o:",
    "label": "countdown o"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/crossmark.gif",
    "token": ":challenge/crossmark:",
    "label": "crossmark"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/deaf-guess.gif",
    "token": ":challenge/deaf-guess:",
    "label": "deaf guess"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/deserved.gif",
    "token": ":challenge/deserved:",
    "label": "deserved"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/drop-down.gif",
    "token": ":challenge/drop-down:",
    "label": "drop down"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/drop-streak.gif",
    "token": ":challenge/drop-streak:",
    "label": "drop streak"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/drunk-vision.gif",
    "token": ":challenge/drunk-vision:",
    "label": "drunk vision"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/fanboy.gif",
    "token": ":challenge/fanboy:",
    "label": "fanboy"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/guessingoat.gif",
    "token": ":challenge/guessingoat:",
    "label": "guessingoat"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/hint-reflexes.gif",
    "token": ":challenge/hint-reflexes:",
    "label": "hint reflexes"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/in-and-out.gif",
    "token": ":challenge/in-and-out:",
    "label": "in and out"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/instalike.png",
    "token": ":challenge/instalike:",
    "label": "instalike"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/internet-explorer.gif",
    "token": ":challenge/internet-explorer:",
    "label": "internet explorer"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/is-that-a-mod.gif",
    "token": ":challenge/is-that-a-mod:",
    "label": "is that a mod"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/made-you-squint.gif",
    "token": ":challenge/made-you-squint:",
    "label": "made you squint"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/mogged.gif",
    "token": ":challenge/mogged:",
    "label": "mogged"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/monochromism.gif",
    "token": ":challenge/monochromism:",
    "label": "monochromism"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/my-eyes-are-bleeding.png",
    "token": ":challenge/my-eyes-are-bleeding:",
    "label": "my eyes are bleeding"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/my-favorite-color-is-red.gif",
    "token": ":challenge/my-favorite-color-is-red:",
    "label": "my favorite color is red"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/need-some-space.gif",
    "token": ":challenge/need-some-space:",
    "label": "need some space"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/noob-vs-pro-vs-hacker.gif",
    "token": ":challenge/noob-vs-pro-vs-hacker:",
    "label": "noob vs pro vs hacker"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/omg-hacker.gif",
    "token": ":challenge/omg-hacker:",
    "label": "omg hacker"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/ouch.gif",
    "token": ":challenge/ouch:",
    "label": "ouch"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/owner-of-the-lobby.gif",
    "token": ":challenge/owner-of-the-lobby:",
    "label": "owner of the lobby"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/paparazzid.gif",
    "token": ":challenge/paparazzid:",
    "label": "paparazzid"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/picasso.gif",
    "token": ":challenge/picasso:",
    "label": "picasso"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/pointsmaxxing.gif",
    "token": ":challenge/pointsmaxxing:",
    "label": "pointsmaxxing"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/quickscope.gif",
    "token": ":challenge/quickscope:",
    "label": "quickscope"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/reflexes-like-a-cat.gif",
    "token": ":challenge/reflexes-like-a-cat:",
    "label": "reflexes like a cat"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/settings.gif",
    "token": ":challenge/settings:",
    "label": "settings"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/skribbl-duels-logo.gif",
    "token": ":challenge/skribbl-duels-logo:",
    "label": "skribbl duels logo"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/smol-words.gif",
    "token": ":challenge/smol-words:",
    "label": "smol words"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/sniper.gif",
    "token": ":challenge/sniper:",
    "label": "sniper"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/solitary.gif",
    "token": ":challenge/solitary:",
    "label": "solitary"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/spamguessing.gif",
    "token": ":challenge/spamguessing:",
    "label": "spamguessing"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/through-thick-and-thin.gif",
    "token": ":challenge/through-thick-and-thin:",
    "label": "through thick and thin"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/time-waste.gif",
    "token": ":challenge/time-waste:",
    "label": "time waste"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/tldr.gif",
    "token": ":challenge/tldr:",
    "label": "tldr"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/transcended.gif",
    "token": ":challenge/transcended:",
    "label": "transcended"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/type-racer.gif",
    "token": ":challenge/type-racer:",
    "label": "type racer"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/ultimate-comeback.gif",
    "token": ":challenge/ultimate-comeback:",
    "label": "ultimate comeback"
  },
  {
    "group": "challenge",
    "path": "res/challenge-icons/wpmaster.gif",
    "token": ":challenge/wpmaster:",
    "label": "wpmaster"
  },
  {
    "group": "friend",
    "path": "res/friend-system/block.gif",
    "token": ":friend/block:",
    "label": "block"
  },
  {
    "group": "friend",
    "path": "res/friend-system/friends-list.gif",
    "token": ":friend/friends-list:",
    "label": "friends list"
  },
  {
    "group": "friend",
    "path": "res/friend-system/ping.gif",
    "token": ":friend/ping:",
    "label": "ping"
  },
  {
    "group": "skribble",
    "path": "res/skribble-icons/correct.gif",
    "token": ":skribble/correct:",
    "label": "correct"
  },
  {
    "group": "skribble",
    "path": "res/skribble-icons/incorrect.gif",
    "token": ":skribble/incorrect:",
    "label": "incorrect"
  },
  {
    "group": "skribble",
    "path": "res/skribble-icons/semicorrect.gif",
    "token": ":skribble/semicorrect:",
    "label": "semicorrect"
  },
  {
    "group": "skribble",
    "path": "res/skribble-icons/skribbl-coin.gif",
    "token": ":skribble/skribbl-coin:",
    "label": "skribbl coin"
  },
  {
    "group": "slot",
    "path": "res/skribbl-slots/slot-icons/7.gif",
    "token": ":slot/7:",
    "label": "7"
  },
  {
    "group": "slot",
    "path": "res/skribbl-slots/slot-icons/eraser.gif",
    "token": ":slot/eraser:",
    "label": "eraser"
  },
  {
    "group": "slot",
    "path": "res/skribbl-slots/slot-icons/heart.gif",
    "token": ":slot/heart:",
    "label": "heart"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/average-guess-time.gif",
    "token": ":stat/average-guess-time:",
    "label": "average guess time"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/average-guess-wpm.gif",
    "token": ":stat/average-guess-wpm:",
    "label": "average guess wpm"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/average-typing-wpm.gif",
    "token": ":stat/average-typing-wpm:",
    "label": "average typing wpm"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/best-guess-wpm.gif",
    "token": ":stat/best-guess-wpm:",
    "label": "best guess wpm"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/best-private-score.gif",
    "token": ":stat/best-private-score:",
    "label": "best private score"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/best-public-score.gif",
    "token": ":stat/best-public-score:",
    "label": "best public score"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/best-typing-wpm.gif",
    "token": ":stat/best-typing-wpm:",
    "label": "best typing wpm"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/distinct-lobbies.gif",
    "token": ":stat/distinct-lobbies:",
    "label": "distinct lobbies"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/duel-matches.gif",
    "token": ":stat/duel-matches:",
    "label": "duel matches"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/duel-win-rate.gif",
    "token": ":stat/duel-win-rate:",
    "label": "duel win rate"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/duel-win-streak.gif",
    "token": ":stat/duel-win-streak:",
    "label": "duel win streak"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/duel-wins.gif",
    "token": ":stat/duel-wins:",
    "label": "duel wins"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/guess-time-trend.gif",
    "token": ":stat/guess-time-trend:",
    "label": "guess time trend"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/guess-wpm-trend.gif",
    "token": ":stat/guess-wpm-trend:",
    "label": "guess wpm trend"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/guessed-word-coverage.gif",
    "token": ":stat/guessed-word-coverage:",
    "label": "guessed word coverage"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/lobby-sessions.gif",
    "token": ":stat/lobby-sessions:",
    "label": "lobby sessions"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/median-guess-time.gif",
    "token": ":stat/median-guess-time:",
    "label": "median guess time"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/median-guess-wpm.gif",
    "token": ":stat/median-guess-wpm:",
    "label": "median guess wpm"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/median-typing-wpm.gif",
    "token": ":stat/median-typing-wpm:",
    "label": "median typing wpm"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/p90-guess-wpm.gif",
    "token": ":stat/p90-guess-wpm:",
    "label": "p90 guess wpm"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/p90-typing-wpm.gif",
    "token": ":stat/p90-typing-wpm:",
    "label": "p90 typing wpm"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/pin.gif",
    "token": ":stat/pin:",
    "label": "pin"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/seen-word-coverage.gif",
    "token": ":stat/seen-word-coverage:",
    "label": "seen word coverage"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/social-actions.gif",
    "token": ":stat/social-actions:",
    "label": "social actions"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/trash.gif",
    "token": ":stat/trash:",
    "label": "trash"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/typing-trend.gif",
    "token": ":stat/typing-trend:",
    "label": "typing trend"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/unique-users-seen.gif",
    "token": ":stat/unique-users-seen:",
    "label": "unique users seen"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/unique-words-guessed.gif",
    "token": ":stat/unique-words-guessed:",
    "label": "unique words guessed"
  },
  {
    "group": "stat",
    "path": "res/stat-icons/unique-words-seen.gif",
    "token": ":stat/unique-words-seen:",
    "label": "unique words seen"
  }
] as const;
export const ADDITIONAL_SOCIAL_EMOJI_ASSETS: Readonly<Record<string, string>> = {};
