// Generated by scripts/generate-sound-assets.cjs. Do not edit.
export const SOUND_ASSET_PATHS = {
  "queueJoin": "sound-effects/join-queue.ogg",
  "queueLeave": "sound-effects/leave-queue.ogg",
  "countdownTick": "sound-effects/countdown.ogg",
  "challengeCompletion": "sound-effects/challenge-completion.ogg",
  "matchChatPing": "sound-effects/match-chat.ogg",
  "matchFound": "sound-effects/match-found.ogg",
  "intro": "sound-effects/intro.ogg",
  "matchWin": "sound-effects/match-win.ogg"
} as const;
export type SoundEffectId = keyof typeof SOUND_ASSET_PATHS;
export const EMBEDDED_SOUND_ASSETS: Readonly<Partial<Record<SoundEffectId, string>>> = {};
